# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d28dfd825f8d8f17f454671b34ead0533770ff01dca179eb1c60d2cdd065d6b43c4430604c51ef79d819bfcefe777ef930858a899700a8ad193ad827bfb4b479

test:
  secret_key_base: 712e857a886a23f9f12fce531d5e1db431ed771cca0bd9791b9352a6e6d485dc77cccfbf4b3ecfb6be203ac17b6d21a099e9afbab6c51c4fea5174545367899b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
